import React from 'react'

export const CountryCodes=[
      {label: 'AF', value: 'AF'},
    //   {label: 'AL', value: 'AL'},
    //   {label: 'AS', value: 'AS'},
    //   {label: 'AD', value: 'AD'},
    //   {label: 'AO', value: 'AO'},
    //   {label: 'AI', value: 'AI'},
    //   {label: 'AQ', value: 'AQ'},
    //   {label: 'AG', value: 'AG'},
    //   {label: 'AR', value: 'AR'},
    //   {label: 'AM', value: 'AM'},
    //   {label: 'AW', value: 'AW'},
      {label: 'AU', value: 'AU'},
    //   {label: 'AT', value: 'AT'},
      {label: 'AZ', value: 'AZ'},
    //   {label: 'BS', value: 'BS'},
    //   {label: 'BH', value: 'BH'},
      {label: 'BD', value: 'BD'},
    //   {label: 'BB', value: 'BB'},
    //   {label: 'BY', value: 'BY'},
      {label: 'BE', value: 'BE'},
    //   {label: 'BZ', value: 'BZ'},
    //   {label: 'BJ', value: 'BJ'},
    //   {label: 'BM', value: 'BM'},
    //   {label: 'BT', value: 'BT'},
    //   {label: 'BO', value: 'BO'},
    //   {label: 'BA', value: 'BA'},
    //   {label: 'BW', value: 'BW'},
    //   {label: 'CL', value: 'CL'},
    //   {label: 'CN', value: 'CN'},
    //   {label: 'CX', value: 'CX'},
    //   {label: 'CC', value: 'CC'},
    //   {label: 'CO', value: 'CO'},
    //   {label: 'CR', value: 'CR'},

    //   {label: 'CU', value: 'CU'},
    //   {label: 'CW', value: 'CW'},
    //   {label: 'CY', value: 'CY'},
    //   {label: 'CZ', value: 'CZ'},
    //   {label: 'CD', value: 'CD'},
    //   {label: 'CR', value: 'CR'},
      {label: 'DK', value: 'DK'},
    //   {label: 'DJ', value: 'DJ'},
    //   {label: 'DM', value: 'DM'},
    //   {label: 'TL', value: 'TL'},
    //   {label: 'EC', value: 'EC'},
      {label: 'EG', value: 'EG'},
    //   {label: 'SV', value: 'SV'},
    //   {label: 'GQ', value: 'GQ'},
    //   {label: 'EE', value: 'EE'},
    //   {label: 'FI', value: 'FI'},
      {label: 'FR', value: 'FR'},
    //   {label: 'GM', value: 'GM'},
    //   {label: 'GE', value: 'GE'},
    //   {label: 'GR', value: 'GR'},
    //   {label: 'GD', value: 'GD'},
    //   {label: 'GU', value: 'GU'},
    //   {label: 'GG', value: 'GG'},
    //   {label: 'GN', value: 'GN'},
    //   {label: 'HT', value: 'HT'},
    //   {label: 'HN', value: 'HN'},
      {label: 'HK', value: 'HK'},
    //   {label: 'HU', value: 'HU'},
    //   {label: 'IS', value: 'IS'},
      {label: 'IN', value: 'IN'},
    //   {label: 'ID', value: 'ID'},
      {label: 'IR', value: 'IR'},
      {label: 'IQ', value: 'IQ'},
      {label: 'IE', value: 'IE'},
    //   {label: 'IM', value: 'IM'},
    //   {label: 'IL', value: 'IL'},
    //   {label: 'IT', value: 'IT'},
    //   {label: 'JM', value: 'JM'},
    //   {label: 'JP', value: 'JP'},
    //   {label: 'JE', value: 'JE'},
    //   {label: 'JO', value: 'JO'},
    //   {label: 'KZ', value: 'KZ'},
    //   {label: 'KE', value: 'KE'},
    //   {label: 'KI', value: 'KI'},
      {label: 'KW', value: 'KW'},
    //   {label: 'LB', value: 'LB'},
    //   {label: 'LI', value: 'LI'},
    //   {label: 'LU', value: 'LU'},
    //   {label: 'MO', value: 'MO'},
    //   {label: 'MK', value: 'MK'},
    //   {label: 'MG', value: 'MG'},
    //   {label: 'MW', value: 'MW'},
    //   {label: 'MU', value: 'MU'},
      {label: 'MX', value: 'MX'},
    //   {label: 'MN', value: 'MN'},
      {label: 'MA', value: 'MA'},
    //   {label: 'MM', value: 'MM'},
    //   {label: 'NA', value: 'NA'},
    //   {label: 'NR', value: 'NR'},
    //   {label: 'NP', value: 'NP'},
    //   {label: 'NL', value: 'NL'},
      {label: 'NZ', value: 'NZ'},
    //   {label: 'NI', value: 'NI'},
    //   {label: 'NE', value: 'NE'},
    //   {label: 'NG', value: 'NG'},
      {label: 'KP', value: 'KP'},
    //   {label: 'NP', value: 'NP'},
      {label: 'OM', value: 'OM'},
      {label: 'PK', value: 'PK'},
    //   {label: 'PW', value: 'PW'},
      {label: 'PS', value: 'PS'},
    //   {label: 'PA', value: 'PA'},
    //   {label: 'PY', value: 'PY'},
    //   {label: 'PH', value: 'PH'},
    //   {label: 'PL', value: 'PL'},
      {label: 'PT', value: 'PT'},
      {label: 'QA', value: 'QA'},
    //   {label: 'RO', value: 'RO'},
      {label: 'RU', value: 'RU'},
    //   {label: 'RW', value: 'RW'},
    //   {label: 'ST', value: 'ST'},
      {label: 'SA', value: 'SA'},
    //   {label: 'SN', value: 'SN'},
    //   {label: 'SC', value: 'SC'},
      {label: 'SL', value: 'SL'},
      {label: 'SG', value: 'SG'},
    //   {label: 'SX', value: 'SX'},
    //   {label: 'SB', value: 'SB'},
    //   {label: 'SO', value: 'SO'},
      {label: 'ZA', value: 'ZA'},
      {label: 'KR', value: 'KR'},
    //   {label: 'SS', value: 'SS'},
      {label: 'ES', value: 'ES'},
    //   {label: 'LK', value: 'LK'},
    //   {label: 'SD', value: 'SD'},
    //   {label: 'SR', value: 'SR'},
    //   {label: 'SZ', value: 'SZ'},
    //   {label: 'SE', value: 'SE'},
    //   {label: 'CH', value: 'CH'},
      {label: 'SY', value: 'SY'},
      {label: 'TW', value: 'TW'},
    //   {label: 'TJ', value: 'TJ'},
      {label: 'TH', value: 'TH'},
      {label: 'TR', value: 'TR'},
    //   {label: 'TM', value: 'TM'},
    //   {label: 'UA', value: 'UA'},
    //   {label: 'UG', value: 'UG'},
      {label: 'AE', value: 'AE'},
      {label: 'GB', value: 'GB'},
      {label: 'US', value: 'US'},
    //   {label: 'VU', value: 'VU'},
    //   {label: 'VA', value: 'VA'},
    //   {label: 'VE', value: 'VE'},
    //   {label: 'VN', value: 'VN'},
    //   {label: 'WF', value: 'WF'},
    //   {label: 'EH', value: 'EH'},
    //   {label: 'YE', value: 'YE'},
    //   {label: 'ZM', value: 'ZM'},
    //   {label: 'ZW', value: 'ZW'}
    
]